jobboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from users.views import(
    login_view,
    signup_view,
    contactus,
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("jobs.urls", namespace="jobs")),
    path('employer/', include("employer.urls", namespace="employer")),
    path('users/', include("users.urls", namespace="user")),
    path('login/',login_view, name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("contact/", contactus, name="contact"),
    path('register/', signup_view, name='register'),
  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Job Board Admin"
admin.site.site_title = "Job Board Admin"

jobs/urls.py
from django.urls import path,include
from jobs.views import(
        job_list, 
        job_detail, 
        apply_job,
        homepage, 
        search_view,
        filter_view,
        # main

       
)

app_name = "jobs"


urlpatterns = [
    path('', homepage, name='index'),
    path('jobs-list', job_list, name='job_list'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/apply/', apply_job, name='apply_job'),
    path('search/', search_view, name="search"),
    path('filter/', filter_view, name="filter_view"),
    # path('recommed/',main,name="main")

]

users/urls.py
from django.urls import path,include
from users.views import profile_view,profile_edit, application_view, view_message, application_delete
app_name = "users"


urlpatterns = [
  
    path("profile/userid = <int:id>/",profile_view, name='profile'),
    path("profile/edit/userid = <int:id>/",profile_edit, name='profileedit'),
    path("myapplications/",application_view, name='application_view'),
    path("myapplications/delete/",application_delete, name='application_delete'),
    path('myapplications/view_message/<int:id>', view_message, name="view_message"),


]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator


BOOL_CHOICES = ((True,'Yes'),(False,'No'))

class User(AbstractUser):
#  is_applicant = models.BooleanField(default=True)     
    image = models.ImageField(upload_to='profile/', null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])   
    is_employer = models.BooleanField(choices=BOOL_CHOICES,null=True, blank=True, default=False)
    resume = models.FileField(upload_to='resume/', null=True, blank=True,validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg','pdf'])])


 
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import User
from django import forms
from django.db import transaction
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from .models import Contact
from django.urls import reverse


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Invalid Login Credentials")
        return self.cleaned_data
    
    def login(self,request):
        if request.method == "POST":
            
            username = self.cleaned_data.get('username')
            password = self.cleaned_data.get('password')

            user = authenticate(username=username,password=password)
            return user



class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ( 
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            "is_employer",
            "image",
         
            )
        


    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        # placeholder
        self.fields['first_name'].widget = forms.TextInput(attrs={ 'placeholder': 'First Name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={ 'placeholder': 'Last Name'})
        self.fields['username'].widget = forms.TextInput(attrs={ 'placeholder': 'Username'})
        self.fields['email'].widget = forms.EmailInput(attrs={ 'placeholder': 'Email'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={ 'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={ 'placeholder': 'Password confirmation'})
        self.fields['image'].widget = forms.FileInput(attrs={ 'placeholder': 'Profile Picture'})
       
        #label
        self.fields['first_name'].label = "First Name"
        self.fields['last_name'].label = "Last Name"
        self.fields['username'].label = "Username"
        self.fields['email'].label = "Email"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"
        self.fields['image'].label = "Profile Picture"
        self.fields['is_employer'].label = "Are you an employer?"


        #help text
        self.fields['username'].help_text = "Username must be unique."
        self.fields['email'].help_text = "Email must be unique."
        self.fields['password1'].help_text = "Password must be 8 characters or more and not too common"
        
        



class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ( 
            "first_name",
            "last_name",
            "username",
            "email",
            "image",
            "resume"
            )
       
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control row-4"



        
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['name','email','subject','message' ,'created_at'] 

users/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth import get_user_model
from .models import Contact
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from users.forms import  SignUpForm,ProfileForm, LoginForm, ContactForm
from .models import User
from jobs.models import Application, Message


User = get_user_model()

def jobseeker_check(user):
    return not user.is_employer

# class UserLoginView(LoginView):
#     template_name = "login.html"
   
def login_view(request):
    form = LoginForm(request.POST or None)
    next_url = request.POST.get('next')
    if request.POST and form.is_valid():
        user = form.login(request)
        if not user:
            raise ValueError("Invalid credentials")
        if user:
            login(request,user)
            if next_url:
                return HttpResponseRedirect(next_url)
            if user.is_employer:
                return HttpResponseRedirect(reverse ('employer:dashboard'))
            else:
                return HttpResponseRedirect(reverse ('jobs:index'))
            
    else:
        return render(request,"login.html", {"form":form})



def signup_view(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            if 'resume' in request.FILES:
                resume = request.FILES['resume']
            else:
                resume = None
            insert = form.save(commit=False)
            insert.resume = resume
            insert.save()
            messages.success(request, 'Your account is created successfully')
            return HttpResponseRedirect(reverse ('login'))

        else:
            msg = "form invalid"
    else:
        form = SignUpForm
    return render(request,'register.html', {'form':form, 'msg':msg})

        
@login_required(login_url = 'login')
@user_passes_test(jobseeker_check)
def profile_view(request,id):
    user = get_object_or_404(User,id=id)
    return render(
        request,
        "myprofile.html",
        {"user":user},
    )



@login_required(login_url='login')
@user_passes_test(jobseeker_check)
def profile_edit(request,id):
    user = get_object_or_404(User,id=id)
    form = ProfileForm(request.POST or None,request.FILES or None, instance = request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your profile is updated successfully')
        Application.objects.filter(submitted_by=user).update(resume = user.resume)
        return HttpResponseRedirect(
            reverse(
                "users:profile",
                args=(
                    user.id,
                ),
            )
        )
    
    return render(request,"myprofileedit.html",{"form":form})

@login_required(login_url='login')
@user_passes_test(jobseeker_check)
def application_view(request):
    applications = Application.objects.all()
    return render(
        request,
        "myapplications.html",
        {"applications":applications}
       
    )
@login_required(login_url='login')
@user_passes_test(jobseeker_check)
def application_delete(request):
    applicationid = request.POST.get("applicationid")
    application = get_object_or_404(Application, id=applicationid)
    application.delete()
    return HttpResponseRedirect(reverse("users:application_view"))

@login_required(login_url='login')
@user_passes_test(jobseeker_check)
def view_message(request, id):
    application = Application.objects.get(id = id)
    print(application)
    message = Message.objects.get(application_id = application)
    print(message)
    return render(request, "message.html", {
        "applicaiton":application,
        "message":message,
    })

def contactus(request):
   
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message= request.POST.get('message')
        add = Contact(name=name, email=email, subject=subject, message=message)
        add.save()
        return HttpResponseRedirect(reverse ('jobs:index'))
    else:
        form = ContactForm
    return render(request,'contact.html', {'form':form})

users/templates/myapplications.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>My Applicaitons</title>
{% endblock title %}

{% block content %}

{% include 'navbar.html' %}

{% if applications %}

<section class="seekerprofile" style="background-color: #f5f5f7;">
    <div class="container" style="height: 80vh;">
        <div class="pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h5">My Applications</h1>
        </div>
        {% include 'flashmessage.html' %}
        <div class="row g-4 row-cols-1 row-cols-lg-3">
            {% for application in applications %}
            {% if request.user == application.submitted_by %}
            <div class="feature col" style="width: auto">

                <div class="text-left ps-4 py-4 px-4" style="background-color: #edf0f3; border-radius: 10px">
                    <p class="fw-normal">Resume: <a href="{{ application.resume.url }}"> View Application</a></p>
                    <p class="fw-normal">Submitted For: {{ application.submitted_for }}</p>
                    <p class="fw-normal">Status: {{ application.status }}</p>
                    <p class="fw-normal">Submitted On: {{ application.submitted_on|date:"F d, Y" }}</p>
                    <div class="mt-4" style="border-top: 0.1px solid #bfc3cb">
                        <br>
                        {% if application.status == "Pending" %}
                        <p class="fw-normal">Your application is in pending.</p>
                        {% elif application.status == "Accepted" %}
                        <p class="fw-normal">Your application has been accepted.</p>

                        <a href="{% url 'users:view_message' application.id %}">
                            <button class="px-3" type="submit" value="submit"
                                style="background-color: #B6C6FF; border-radius: 5px; border:none; height: 4vh; width:auto;"
                                onmouseover="this.style.backgroundColor='#8ca3f5';"
                                onmouseout="this.style.backgroundColor='#B6C6FF';"><i class="bi bi-eye me-2"></i>View
                                Message</button>
                        </a>
                        {% elif application.status == "Rejected" %}
                        <p class="fw-normal">Your application has been rejected.</p>

                        <a href="{% url 'users:view_message' application.id %}">
                            <button class="px-3" type="submit" value="submit"
                                style="background-color: #B6C6FF; border-radius: 5px; border:none; height: 4vh; width:auto;"
                                onmouseover="this.style.backgroundColor='#8ca3f5';"
                                onmouseout="this.style.backgroundColor='#B6C6FF';"><i class="bi bi-eye me-2"></i>View
                                Message</button>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>

            {% endif %}
            {% endfor %}



        </div>
    </div>

</section>



{% else %}
<section class="seekerprofile" style="background-color: #f5f5f7; height: auto;">
    <div class="container" style="height: 100vh;">
        <div class="pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h5">My Applications</h1>
        </div>
        {% include 'flashmessage.html' %}
        <p class="fw-normal">You have not applied for any jobs yet.</p>

    </div>

</section>

{% endif %}

{% include 'footer.html' %}

{% endblock content %}

users/templates/myprofile.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
<title>My Profile</title>


{% endblock title %}
{% block content %}

{% include 'navbar.html' %}

<section class="seekerprofile" style="background-color: #f5f5f7; height: auto;">
    <div class="container" style="height: 80vh;">
        <div class="pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h5">My Profile</h1>
        </div>
        {% include 'flashmessage.html' %}
        {% if user.image %}
        <img class="img-fluid rounded mt-3" src="{{user.image.url}}" alt="profile" width="150px" height="120px"
            style="text-align: left;"></img>
        {% else %}
        <img class="img-fluid rounded mt-3" src="{% static '/blank.png' %}" alt="profile" width="150px" height="120px"
            style="text-align: left;"></img>
        {% endif %}
        <div class="table-responsive mt-5">
            <table class="table table-sm" style="text-align: left; width: auto; height: 1vh;">
                <tbody>
                    <tr>
                        <th style="text-align: justify;">Name </th>
                        <td style="text-align: justify;">{{user.first_name}} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: justify;">Username </th>
                        <td style="text-align: justify;">{{ user.username }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: justify;">Email </th>
                        <td style="text-align: justify;">{{ user.email }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="mb-3">
            <div class="mb-3" style="text-align: left;">
                <a href="{% url 'users:profileedit' user.id%}"> <button class="px-5" type="submit" value="submit" style="background-color: #B6C6FF; 
                border-radius: 5px; border:none; height: 4vh; width:auto;">
                        <i class="bi bi-pencil-square pe-2"></i>Edit</button>
                </a>
            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}

{% endblock content %}

users/templates/myprofileedit.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Edit Profile</title>
{% endblock title %}

{% block content %}

{% include 'navbar.html' %}

<section class="seekerprofile" style="background-color: #f5f5f7; height: auto;">
    <form class="container" action="#" name="searchfiler" method="post" enctype="multipart/form-data"> {% csrf_token %}
        <div class="pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h5">Edit Profile</h1>
        </div>
        {% include 'flashmessage.html' %}

        {% for field in form %}

        <div class="mb-3">
            {{ field.label_tag }}
            {{ field }}
            <span class="text text-danger">
                {{field.errors}}
            </span>

        </div>
        {% endfor %}
        <input type="hidden" value='{{request.user}}' readonly>

        <div class="mb-3">
            <div class="mb-3" style="text-align: left;">
                <button class="px-3" type="submit" value="submit"
                    style="background-color: #B6C6FF; border-radius: 5px; border:none; height: 4vh; width:auto;"
                    onmouseover="this.style.backgroundColor='#8ca3f5';"
                    onmouseout="this.style.backgroundColor='#B6C6FF';">Update Profile</button>
            </div>
        </div>
    </form>
</section>

{% endblock content %}