jobboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from users.views import(
    login_view,
    signup_view,
    contactus,
    )


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("jobs.urls", namespace="jobs")),
    path('employer/', include("employer.urls", namespace="employer")),
    path('users/', include("users.urls", namespace="user")),
    path('login/',login_view, name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("contact/", contactus, name="contact"),
    path('register/', signup_view, name='register'),
  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Job Board Admin"
admin.site.site_title = "Job Board Admin"

jobs/urls.py
from django.urls import path,include
from jobs.views import(
        job_list, 
        job_detail, 
        apply_job,
        homepage, 
        search_view,
        filter_view,
        # main

       
)

app_name = "jobs"


urlpatterns = [
    path('', homepage, name='index'),
    path('jobs-list', job_list, name='job_list'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/apply/', apply_job, name='apply_job'),
    path('search/', search_view, name="search"),
    path('filter/', filter_view, name="filter_view"),
    # path('recommed/',main,name="main")

]

users/urls.py
from django.urls import path,include
from users.views import profile_view,profile_edit, application_view, view_message, application_delete
app_name = "users"


urlpatterns = [
  
    path("profile/userid = <int:id>/",profile_view, name='profile'),
    path("profile/edit/userid = <int:id>/",profile_edit, name='profileedit'),
    path("myapplications/",application_view, name='application_view'),
    path("myapplications/delete/",application_delete, name='application_delete'),
    path('myapplications/view_message/<int:id>', view_message, name="view_message"),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    {% block title %}
    <title></title>
    {% endblock title %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block stylesheet %}
    <link rel="icon" href="{% static 'staticfiles/logo.png' %}" type="image/icon type">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'staticfiles/css/style.css' %}">


    {% endblock stylesheet %}


    {% block index %}

    {% endblock index %}
</head>

<body style="background-color: #f5f5f7;">

    {% include 'navbar.html' %}


    {% block content %}



    {% endblock content %}




    {%block script%}
    <script src="{% static 'staticfiles/js/jqueryajax.min.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    {% endblock script%}
</body>



</html>

templates/base_site.html
{% extends 'base.html' %}


{% block maincontent %}

<h1>Welcome to the Job Board!</h1>
<p>Find your dream job or post your open positions.</p>
<a href="{% url 'job_list' %}" class="btn btn-primary">Browse Jobs</a>

{% endblock maincontent %}

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Contact Us</title>
{% endblock title %}

{% block content %}



<section class="contactus" style="background-color: #F7F5EB;">
    <div class="text-center" id="contactus" style="height: 15vh;">
        <h2>Contact Us</h2>
    </div>
</section>
<section style="background-color: #f5f5f7; height: auto;">
    <div class="container">
        <div class="row g-5">
            <!-- ============================================================Right part========================================================= -->
            <div class="col-md-5 col-lg-4 order-md-last"
                style="border-radius: 10px; background-color: #B6C6FF; height: 25vh; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
                <br>
                <p class="d-flex mb-3 mt-3 mx-3"><i class="bi bi-geo-alt me-3"></i>Gorkha, Nepal</p>
                <p class="d-flex mb-3 mx-3"><i class="bi bi-telephone me-3"></i>1800-Number-1800</p>
                <p class="d-flex mb-3 mx-3"><i class="bi bi-inbox-fill me-3"></i>1800-FaxNumber-1800</p>
                <p class="d-flex mb-3 mx-3"><i class="bi bi-envelope-at me-3"></i>into@jobhub.com</p>
                <br>
            </div>

            <!-- ============================================================Left part========================================================= -->
            <div class="col-md-7 col-lg-8"
                style="border: 0.1px solid #bfc3cb; border-radius: 5px; text-align: left; height: 80vh;">
                <h5 class="mb-3 mt-3">Fill Up the form for any Inquity.</h5>
                <form action="" name="searchfiler" method="post"> {% csrf_token %}
                    {% if user.is_authenticated %}
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Full Name:</label>
                        <input type="text" name="name" class="form-control" id="exampleFormControlInput1"
                            value="{{user.first_name}} {{user.last_name}}" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email</label>
                        <input type="text" name="email" class="form-control" id="exampleFormControlInput1"
                            value="{{user.email}}" readonly>
                    </div>
                    {% else %}
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Full Name:</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1">
                    </div>
                    {% endif %}
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Subject</label>
                        <input type="text" name="subject" class="form-control" id="exampleFormControlInput1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Message</label>
                        <textarea class="form-control" name="message" id="exampleFormControlTextarea1"
                            rows="7"></textarea>
                    </div>
                    <div class="mb-3">
                        <div class="mb-3" style="text-align: center;">
                            <button type="submit" value="submit"
                                style="background-color: #B6C6FF; border-radius: 5px; border:none; height: 4vh; width:20vw;">Submit</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</section>
{% include 'footer.html' %}

{% endblock %}

templates/flashmessage.html
{% load static %}

<style>
    .alert {
        width: 50%;
    }
</style>

<script type="text/javascript">
    setTimeout(function () {
        $('.alert').alert('close');
    }, 1000);

</script>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} fade show" role="alert" id="alert">
    <strong>{{ message }}</strong>
</div>
{% endfor %}
{% endif %}

templates/footer.html
{% load static %}

<section class="footer" style="background-color: #ECE9E9;">
    <div class="container">
        <footer class="mt-4 pt-3 pb-2">
            <div class="row mt-2">
                <div class="col-md-6 col-md-1 mb-3">
                    <img class="img-fluid" src="{%static 'staticfiles/logo.png'%}" style="width: 16%; height: 7vh;">
                    <h5 class="pt-2">About JobHub</h5>
                    <h5 class="fw-normal" style="font-size: 16px; width: 90%;">
                        Leading online employment board JobHub connects companies and job seekers.
                        We make it easier for organizations to post job openings and attract top
                        talent by streamlining the job search process.
                        Job searchers can conveniently view openings and submit applications.
                        With a smooth job search, sign up with JobHub today!
                    </h5>
                </div>
                <div class="col-6 col-md-2 mb-3">
                    <h5>Contact Us</h5>
                    <p class="d-flex mb-3 mt-3"><i class="bi bi-geo-alt me-2"></i>Kalanki, Kathmandu</p>
                    <p class="d-flex mb-3"><i class="bi bi-telephone me-2"></i>1800-Number-1800</p>
                    <p class="d-flex mb-3"><i class="bi bi-inbox me-2"></i>1800-FaxNumber-1800</p>
                    <p class="d-flex mb-3"><i class="bi bi-envelope-at me-2"></i>into@jobhub.com</p>
                </div>


            </div>

            <div class="d-flex flex-column flex-sm-row pt-2 border-top border-dark-subtle"
                style="justify-content: center;">
                <ul class="list-unstyled d-flex pt-4">
                    <li class="ms-3"><a class="link-body-emphasis" href="https://www.facebook.com"><i
                                class="bi bi-facebook"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="https://linkedin.com"><i
                                class="bi bi-linkedin"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="https://twitter.com"><i
                                class="bi bi-twitter"></i></a>
                    </li>
                </ul>
            </div>
            <div class="d-flex flex-column flex-sm-row" style="justify-content: center;">
                <p>Made by Human on Earth © 2023 JobHub Company, Inc. All rights reserved.</p></br>
            </div>
        </footer>
    </div>
</section>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>JobHub</title>
{% endblock title %}

{% block content %}

<link rel="stylesheet" href="{% static 'staticfiles/css/home.css' %}">
<section class="main py-5">
  <div class="container py-5">
    <h2>Connecting you to your next career opportunity.</h2>
    <h4>Find the job that fits your skills and passions.</h4>
    <form method="post" name="form" class="searchform" action="{% url 'jobs:search' %}"> {% csrf_token %}
      <input type="text" name="searchtext" placeholder="Search Job"><i class="bi bi-search b1"></i>
    </form>
  </div>
</section>



{% include 'recentjobs.html' %}

{% include 'footer.html' %}

{% endblock %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="{% static 'staticfiles/logo.png' %}" type="image/icon type">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'staticfiles/css/login.css' %}">
	<title>JobHub | Login</title>
</head>

<body>

	<div class="container">
		<form action="" class="login active" method="post"> {% csrf_token %}
			<h1 class="titleh1">JobHub</h1>
			<h3 class="titleh3">Login with your account</h3>
			{% if form.non_field_errors %}
			{% for error in form.non_field_errors %}
			<p style="color: red">{{ error }}</p>
			{% endfor %}
			</ul>
			{% endif %}
			{% include 'flashmessage.html' %}
			<div class="form-group">
				<label for="username">Username</label>
				<div class="input-group">
					<input type="username" id="username" name="username" placeholder="Enter your username">
					<i class='bi bi-person'></i>
				</div>
			</div>
			<div class="form-group">
				<label for="password">Password</label>
				<div class="input-group">
					<input type="password" id="password" name="password" placeholder="Your password">
					<i class='bi bi-lock'></i>
				</div>
				<span class="help-text">At least 8 characters</span>
			</div>
			<button type="submit" class="btn-submit" name="submit">Login</button>
			<a href="#">Forgot password?</a>
			<p>I don't have an account? <a href="{% url 'register' %}">Register</a></p>
			<a href="{% url 'jobs:index' %}">Go home</a>

			<input type="hidden" name="next" value="{{ request.GET.next }}" />
		</form>
	</div>
</body>
<script src="{% static 'staticfiles/js/jqueryajax.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
	crossorigin="anonymous"></script>

</html>

templates/navbar.html
{% load static %}

<section class="header">
  <nav class="navbar navbar-expand-lg fixed-top"
    style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); background-color: #F7F5EB;">
    <div class="container">
      <img src="{%static 'staticfiles/logo.png'%}" alt="logo" width="30" height="24">
      <a class="navbar-brand mx-2" href="{% url 'jobs:index' %}">JobHub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item mx-3">
            <a class="nav-link active" aria-current="page" href="{% url 'jobs:index' %}">Home</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'jobs:job_list' %}">Jobs</a>
          </li>

          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>





        </ul>
        <div class="d-flex">
          <!-- ========================================after login======================================== -->
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                {{request.user.first_name}} <i class="bi bi-person-circle ms-2"></i>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'users:profile' user.id %}"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">My Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'users:application_view'%}"
                    onmouseover="this.style.color='#007BFF';" onmouseout="this.style.color='#000';">My Application</a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'logout' %}" onmouseover="this.style.color='#007BFF';"
                    onmouseout="this.style.color='#000';">Log Out</a></li>
              </ul>
            </li>
          </ul>
          {% endif %}


          <!-- ========================================after login======================================== -->

          <div class="d-flex">
            {% if not request.user.is_authenticated %}
            <a href="{% url 'login' %}"> <button class="button-60" role="button">Login</button> </a>
            <a href="{% url 'register' %}"> <button class="button-600 mx-3" role="button">Register</button> </a>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  </nav>
</section>

templates/recentjobs.html
<style>
    a {
        display: block;
        text-decoration: none;
    }
</style>

<section class="card">
    <div class="container" id="cardtext">Recently Added Jobs</div>
    <div class="container" id="cardcontainer">
        {% for job in jobs %}
        <a href="{% url 'jobs:job_detail' job.id %}">
            <div id="cardbox">

                <div class="card flex-row"><img class="card-img-left example-card-img-responsive" src="{{job.logo.url}}"
                        width="100px" height="120px" />
                    <div class="card-body">
                        <h4 class="fw-bold fs-5" style="color: #0d1e5c;">{{job.title}}</h4>
                        <h4 class="fw-bold fs-6">Category: {{job.category}}</h4>
                        <h4 class="fw-bold fs-6">Level:{{job.level}}</h4>
                        <h4 class="fw-bold fs-6">Type:{{job.type}}</h4>
                        <h5 class="fw-bolder fs-6">Company: {{ job.company_name }}</h5>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>

</section>

templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'staticfiles/css/register.css' %}">
    <title>JobHub | Registration</title>

</head>


<body>

    <div class="container">
        <form action="#" class="register" method="post" enctype="multipart/form-data"> {% csrf_token %}
            <h1 class="titleh1">JobHub | Register your account</h1>


            {% for field in form %}

            <div class="form-group">
                {{ field.label_tag }}<br>

                <div class="input-group">
                    {{ field }}
                    {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>

            {% endfor %}

            <div class="form-group" id="resume">
                <label for="resume">Upload Your Resume:</label><br>

                <div class="input-group">
                    <input type="file" name="resume" placeholder="Upload Your Resume">


                </div>
            </div>


            <div>
                <button type="submit" name="submit" class="btn-submit">Register</button>
            </div>

            <p>I already have an account. <a href="{% url 'login' %}">Login</a></p>
            <a href="{% url 'jobs:index' %}">Go home</a>
        </form>
    </div>

</body>
<script type="text/javascript">
    const dropdown = document.getElementById("id_is_employer");
    const targetDiv = document.getElementById("resume");

    dropdown.addEventListener("change", function () {
        // Get the selected option value
        const selectedOption = dropdown.value;

        // Check the selected value and show/hide the targetDiv accordingly
        if (selectedOption === "False") {
            targetDiv.style.display = "block"; // or targetDiv.style.visibility = 'visible';
        } else {
            targetDiv.style.display = "none"; // or targetDiv.style.visibility = 'hidden';
        }
    });
</script>

</html>